modVersion=1.0.16
hytaleServerVersion=0.6.5
hytaleGameVersionId=14284
hytaleGameVersionName=Early Access
artifactBaseName=NoHostileMobSpawn
artifactDisplayName=Elemental Harmony
curseForgeProjectSlug=elemental-harmony
