modVersion=1.0.7
hytaleServerVersion=0.5.4
hytaleGameVersionId=14284
hytaleGameVersionName=Early Access
artifactBaseName=NoHostileMobSpawn
artifactDisplayName=Elemental Harmony
curseForgeProjectSlug=elemental-harmony
